/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Authors {
  bio: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  nationality: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface Books {
  author_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  publication_year: number;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface LoanHistory {
  action: string;
  id: Generated<string>;
  loan_id: string;
  occurred_at: Generated<Timestamp>;
}

export interface Loans {
  book_id: string;
  borrowed_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  due_date: Timestamp;
  id: Generated<string>;
  member_id: string;
  returned_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Members {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  authors: Authors;
  books: Books;
  loan_history: LoanHistory;
  loans: Loans;
  members: Members;
}
