AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Library API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: latest
