name: "DEPLOY FRONTEND"

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup pnpm & Node
        uses: ./.github/actions/setup
        with:
          filter: "@root/frontend"
      - name: Build
        run: pnpm --filter @root/frontend build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=library-eembouz-com
